### PR TITLE
Implemented largest substring removal

### LINKED ISSUE #3: Strip off common tokens at the beginning of strings
There are some anomalous cases like the license file for `cmaps` (Adobe color maps?)

```
%%Copyright: -----------------------------------------------------------
%%Copyright: Copyright 1990-2009 Adobe Systems Incorporated.
%%Copyright: All rights reserved.
%%Copyright:
%%Copyright: Redistribution and use in source and binary forms, with or
%%Copyright: without modification, are permitted provided that the
%%Copyright: following conditions are met:
%%Copyright:
%%Copyright: Redistributions of source code must retain the above
%%Copyright: copyright notice, this list of conditions and the following
%%Copyright: disclaimer.
%%Copyright:
%%Copyright: Redistributions in binary form must reproduce the above
%%Copyright: copyright notice, this list of conditions and the following
%%Copyright: disclaimer in the documentation and/or other materials
%%Copyright: provided with the distribution.
%%Copyright:
%%Copyright: Neither the name of Adobe Systems Incorporated nor the names
%%Copyright: of its contributors may be used to endorse or promote
%%Copyright: products derived from this software without specific prior
%%Copyright: written permission.
%%Copyright:
%%Copyright: THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
%%Copyright: CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
%%Copyright: INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
%%Copyright: MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
%%Copyright: DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
%%Copyright: CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
%%Copyright: SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
%%Copyright: NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
%%Copyright: LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
%%Copyright: HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
%%Copyright: CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
%%Copyright: OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
%%Copyright: SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
%%Copyright: -----------------------------------------------------------
```

Shouldn't be too difficult to detect the common string `%%Copyright: ` at the start and strip it off. [LCS](https://en.wikipedia.org/wiki/Longest_common_substring_problem) is probably the way to go.

### PR DESCRIPTION
**Pull request by JoshBrudnak**
Resolves #3

Added a step to the preprocessing to remove the largest substring from a license. I also added testing of the function.

### CODE REVIEW

**Comment by JoshBrudnak** [comment]
@jpeddicord It is able to find the largest substr and remove it from in all occurences except for the first occurance. Here's an example ->

Before largest substr removal: 
```
%%Copyright: Copyright                                                           
%%Copyright: All rights reserved.                                                        
%%Copyright: Redistribution and use in source and binary forms, with or                  
%%Copyright: without modification, are permitted provided that the                       
%%Copyright: following conditions are met:
```

After: 
```
%%Copyright: Copyright
All rights reserved.
Redistribution and use in source and binary forms, with or
without modification, are permitted provided that the
following conditions are met:
```
Do you know what might be causing this?

**Comment by jpeddicord** [comment]
Thanks for the PR! I forgot to take a look at this yesterday; did you figure that out in your latest commit?

For some reason the Travis build is failing, though it looks like it should have succeeded. I'll give that a kick and debug that if it's still stuck.

**Comment by jpeddicord** [comment]
Also: can you confirm that your changes are being submitted under the terms of the Apache 2.0 license?

**Comment by JoshBrudnak** [comment]
Yes, I simply forgot to trim the string before the comparison :face_with_head_bandage: . I did make the changes under the terms of the Apache 2.0 license.

**Comment by JoshBrudnak** [comment]
I refactored the LCS to remove common substrings only if they appear at the beginning of a line. This seems to have fixed the failing test. I also added the extra tests that you provided. Thanks :100: .

**Comment by jpeddicord** [comment]
This looks great! Thanks for fixing that up. I might tinker with the order of the substring removal down the line (it might be more efficient to put it in the "normalize" list instead of "aggressive", so it'll get more heavily cached) but as it is this'll work just fine.

**Pull request merged**
