### PR TITLE
AppVeyor: Enable symlinks before cloning

### PR DESCRIPTION
**Pull request by sschuberth**
*Description of changes:*

 This way we can get rid of the clean-up / reset performed.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jpeddicord** [comment]
Ah! That's much cleaner. For some reason the AppVeyor check has stalled out and is preventing me from merging. I'll come back to this in a couple hours and see if that's cleared out; if it hasn't I'll remove that from the protected branch options and merge.

Thanks for the change!

**Comment by sschuberth** [comment]
I just did a dummy `amend` to force retriggering the builds.

**Comment by jpeddicord** [comment]
I have a hunch that AppVeyor isn't configured to run on pull requests, since it hasn't started anything on the build account.. I'll shut that off for now and diagnose separately.

**Comment by jpeddicord** [comment]
This actually failed to build in the end (same symlink issue):

https://ci.appveyor.com/project/jpeddicord/askalono/build/master-4

I recall strangeness here last time it happened. Something weird when running git commands before the repo was cloned.

**Comment by sschuberth** [comment]
Ah, right, I now recall that [core.symlinks](https://git-scm.com/docs/git-config#git-config-coresymlinks) defaults to `true` anyway, but `clone` will probe the underlying file systems and eventually change the default. I have another idea what to try out, and will do so in my fork first now.

**Comment by sschuberth** [comment]
So that was an interesting case to debug, but I finally found out what's going on, see the commit message of PR https://github.com/amzn/askalono/pull/31.

**Pull request merged**
